apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-node
  template:
    metadata:
      labels:
        app: helloworld-node
    spec:
      containers:
      - name: helloworld-node
        image: luanavbrito/helloworld-node
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-node-service
spec:
  type: NodePort
  selector:
    app: helloworld-node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3030
    nodePort: 30001